import Link from "next/link";

export default function PrivacyPage() {
    return (
        <div className="flex flex-col w-full bg-rl-black min-h-screen">
            {/* Hero */}
            <section className="relative py-40 overflow-hidden flex flex-col items-center justify-center text-center w-full bg-rl-dark-grey border-b border-rl-white/10">
                <div className="absolute inset-0 z-0 opacity-40 mix-blend-screen bg-[url('/media/images/hero-ocean.png')] bg-cover bg-center" />
                <div className="relative z-20 max-w-[1400px] px-6 mt-16">
                    <span className="text-rl-light-grey font-bold tracking-[0.3em] uppercase mb-4 block text-xs sm:text-sm">
                        Privacy Policy
                    </span>
                    <h1 className="text-4xl sm:text-6xl md:text-8xl lg:text-9xl font-heading font-black text-rl-white mb-6 tracking-tighter uppercase">
                        PRIVACY
                    </h1>
                    <p className="text-xl md:text-2xl text-rl-light-grey/90 font-light leading-relaxed max-w-3xl mx-auto">
                        How DIU Skyward handles the information you share—so your applications and messages reach us safely.
                    </p>
                </div>
            </section>

            {/* Content */}
            <section className="py-32 w-full">
                <div className="max-w-[1400px] mx-auto px-6">
                    <div className="max-w-3xl mx-auto space-y-10">
                        <div className="border border-rl-white/20 bg-rl-dark-grey/40 p-10 md:p-16">
                            <h2 className="text-3xl md:text-4xl font-heading font-bold mb-6 tracking-tight">
                                Who we are
                            </h2>
                            <p className="text-rl-light-grey font-light leading-relaxed text-lg">
                                DIU Skyward is a student-led aerospace engineering initiative at Daffodil International University.
                                This Privacy Policy explains how we handle personal information when you visit our website and when you submit
                                information through our forms (like “Careers / Join” and “Contact”).
                            </p>
                            <p className="text-rl-light-grey font-light leading-relaxed text-lg mt-6">
                                Questions or requests? Email{" "}
                                <a
                                    href="mailto:diuskyward.diuarc@gmail.com"
                                    className="text-rl-white hover:text-rl-light-grey transition-colors underline underline-offset-4"
                                >
                                    diuskyward.diuarc@gmail.com
                                </a>
                                .
                            </p>
                        </div>

                        <div className="border border-rl-white/20 bg-rl-dark-grey/40 p-10 md:p-16">
                            <h2 className="text-3xl md:text-4xl font-heading font-bold mb-6 tracking-tight">
                                Information we collect
                            </h2>
                            <p className="text-rl-light-grey font-light leading-relaxed text-lg mb-6">
                                We collect personal information you provide to us, and information generated by standard website use.
                            </p>
                            <ul className="list-disc pl-6 space-y-3 text-rl-light-grey font-light text-lg">
                                <li>
                                    <span className="text-rl-white/90 font-bold">Join form (applications)</span>: full name, student ID, department,
                                    division, and your message.
                                </li>
                                <li>
                                    <span className="text-rl-white/90 font-bold">Contact form (messages)</span>: name, email address, subject (optional),
                                    and message content.
                                </li>
                                <li>
                                    <span className="text-rl-white/90 font-bold">Device & usage data</span>: for example, your IP address and general
                                    browser/device information generated through normal server logging.
                                </li>
                            </ul>
                            <p className="text-rl-light-grey font-light leading-relaxed text-lg mt-6">
                                If you choose not to provide required form fields, we may be unable to process your application or respond to your inquiry.
                            </p>
                        </div>

                        <div className="border border-rl-white/20 bg-rl-dark-grey/40 p-10 md:p-16">
                            <h2 className="text-3xl md:text-4xl font-heading font-bold mb-6 tracking-tight">
                                How we use information
                            </h2>
                            <ul className="list-disc pl-6 space-y-3 text-rl-light-grey font-light text-lg">
                                <li>To review and process applications submitted via the Join form.</li>
                                <li>To respond to questions and messages submitted via the Contact form.</li>
                                <li>To maintain and improve our website experience.</li>
                                <li>To prevent fraud, abuse, and security issues.</li>
                            </ul>
                            <p className="text-rl-light-grey font-light leading-relaxed text-lg mt-6">
                                We use personal information only for purposes consistent with this policy and applicable law.
                            </p>
                        </div>

                        <div className="border border-rl-white/20 bg-rl-dark-grey/40 p-10 md:p-16">
                            <h2 className="text-3xl md:text-4xl font-heading font-bold mb-6 tracking-tight">
                                How we share information
                            </h2>
                            <p className="text-rl-light-grey font-light leading-relaxed text-lg mb-6">
                                We do not sell your personal information. We may share data with service providers that help us run the website.
                            </p>
                            <ul className="list-disc pl-6 space-y-3 text-rl-light-grey font-light text-lg">
                                <li>
                                    <span className="text-rl-white/90 font-bold">Supabase</span>: we store Join and Contact submissions in our Supabase database.
                                </li>
                                <li>
                                    <span className="text-rl-white/90 font-bold">Hosting & infrastructure providers</span>: companies that provide web hosting and
                                    related services (so the site can run).
                                </li>
                                <li>
                                    <span className="text-rl-white/90 font-bold">Embedded video providers</span>: our pages may embed YouTube content; YouTube may collect
                                    cookies and usage data when you view embedded videos.
                                </li>
                            </ul>
                            <p className="text-rl-light-grey font-light leading-relaxed text-lg mt-6">
                                We may disclose information if required by law, or if we believe disclosure is necessary to protect our rights, safety, or integrity of the service.
                            </p>
                        </div>

                        <div className="border border-rl-white/20 bg-rl-dark-grey/40 p-10 md:p-16">
                            <h2 className="text-3xl md:text-4xl font-heading font-bold mb-6 tracking-tight">
                                Security
                            </h2>
                            <p className="text-rl-light-grey font-light leading-relaxed text-lg">
                                We take reasonable technical and organizational measures designed to protect personal information. No method of transmission or storage is perfectly secure.
                                If you believe your personal information has been compromised, contact us using the email above.
                            </p>
                        </div>

                        <div className="border border-rl-white/20 bg-rl-dark-grey/40 p-10 md:p-16">
                            <h2 className="text-3xl md:text-4xl font-heading font-bold mb-6 tracking-tight">
                                Retention & your rights
                            </h2>
                            <p className="text-rl-light-grey font-light leading-relaxed text-lg mb-6">
                                We retain personal information for as long as needed to fulfill the purposes described in this policy (for example, processing applications and handling messages),
                                and we may delete or anonymize data when it is no longer necessary.
                            </p>
                            <ul className="list-disc pl-6 space-y-3 text-rl-light-grey font-light text-lg">
                                <li>You may request access to, correction of, or deletion of your personal information where applicable.</li>
                                <li>You may withdraw consent where consent is the lawful basis for processing.</li>
                                <li>You may object to certain processing activities where applicable.</li>
                            </ul>
                            <p className="text-rl-light-grey font-light leading-relaxed text-lg mt-6">
                                To exercise your rights, email us at{" "}
                                <a
                                    href="mailto:diuskyward.diuarc@gmail.com"
                                    className="text-rl-white hover:text-rl-light-grey transition-colors underline underline-offset-4"
                                >
                                    diuskyward.diuarc@gmail.com
                                </a>
                                .
                            </p>
                        </div>

                        <div className="pt-6 text-center">
                            <Link
                                href="/"
                                className="inline-block px-10 py-4 border border-rl-white text-rl-white hover:bg-rl-white hover:text-rl-black transition-all duration-300 text-xs sm:text-sm font-bold tracking-widest uppercase"
                            >
                                Back to Home
                            </Link>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    );
}

